margin = 100
remove_extra_newlines = true
whitespace_in_kwargs = true
conditional_to_if = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
whitespace_ops_in_indices = true
always_for_in = true
